name: Deploy

on:
  push:
    branches:
      - setup-next-js

  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "bduk-website" #Must be unique in Heroku
          heroku_email: "team@blackdevs.uk"