name: Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  pull_request_target:
    branches: [ master ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout Git Repo
        uses: actions/checkout@v2
      - run: yarn install
      - run: yarn run build

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Git Repo
        uses: actions/checkout@v2
      - run: yarn install
      - run: yarn run build
      - run: yarn test
        env:
          CI: true


  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
     - name: Deploy to Heroku
       uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
       with:
         heroku_api_key: ${{secrets.HEROKU_API_KEY}}
         heroku_app_name: "bduk-website" #Must be unique in Heroku
         heroku_email: "team@blackdevs.uk"
